import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { test } from 'node:test'

const mainSource = readFileSync(new URL('../../src/main/main.ts', import.meta.url), 'utf8')
const windowSource = readFileSync(new URL('../../src/main/window.ts', import.meta.url), 'utf8')
const appSource = readFileSync(new URL('../../src/renderer/app/App.tsx', import.meta.url), 'utf8')
const indexSource = readFileSync(new URL('../../index.html', import.meta.url), 'utf8')
const stylesSource = readFileSync(new URL('../../src/renderer/styles/index.css', import.meta.url), 'utf8')
const preloadSource = readFileSync(new URL('../../src/preload/index.ts', import.meta.url), 'utf8')
const openingSequenceSource = readFileSync(new URL('../../src/shared/opening-sequence.ts', import.meta.url), 'utf8')

test('opening animation uses a compact primary-window presentation without a second BrowserWindow', () => {
  assert.doesNotMatch(mainSource, /createOpeningSplashWindow|showMainWindowAfterOpening/)
  assert.equal(existsSync(new URL('../../src/main/opening-splash.ts', import.meta.url)), false)
  assert.match(mainSource, /isOpeningAnimationEnabled\(currentSettings\)/)
  assert.match(mainSource, /showInitially:\s*!openingEnabled/)
  assert.match(mainSource, /showWhenReady:\s*openingEnabled/)
  assert.match(mainSource, /openingPresentation:\s*openingEnabled/)
  assert.match(mainSource, /openingHandledBySplash:\s*false/)
  assert.match(windowSource, /show:\s*options\?\.showInitially/)
  assert.match(windowSource, /if \(options\.showWhenReady/)
  assert.match(windowSource, /screen\.getDisplayMatching|screen\.getPrimaryDisplay/)
  assert.match(windowSource, /const openingBounds/)
  assert.match(windowSource, /roundedWindowShape\(openingWidth, openingHeight, OPENING_PRESENTATION\.cornerRadius\)/)
  assert.match(windowSource, /mainWindow\.setShape\(\[\]\)/)
  assert.match(windowSource, /resizable:\s*!openingPresentation/)
  assert.match(windowSource, /frame:\s*!openingPresentation/)
  assert.match(windowSource, /hasShadow:\s*!openingPresentation/)
  assert.match(windowSource, /accentColor:\s*'#030406'/)
  assert.match(windowSource, /mainWindow\.setHasShadow\(true\)/)
  assert.match(windowSource, /mainWindow\.setAccentColor\(null\)/)
  assert.match(windowSource, /mainWindow\.hide\(\)[\s\S]*mainWindow\.setBounds\(targetBounds/)
  assert.match(windowSource, /OPENING_COMPLETE_IPC_CHANNEL/)
  assert.match(openingSequenceSource, /width:\s*680/)
  assert.match(openingSequenceSource, /height:\s*400/)
  assert.match(openingSequenceSource, /cornerRadius:\s*28/)
  assert.match(indexSource, /__vastOpeningStartupEnabled=params\.get\('vastOpening'\)===\s*'1'/)
  assert.doesNotMatch(indexSource, /__vastOpeningStartedAt/)
  assert.doesNotMatch(indexSource, /vast-static-opening/)
  assert.match(appSource, /className="vast-opening-backdrop"/)
  assert.match(appSource, /className="vast-opening-logo-halo"/)
  assert.match(appSource, /startupOpeningRunsInMain/)
  assert.match(appSource, /const remainingMs = OPENING_SEQUENCE\.overlayHideMs/)
  assert.doesNotMatch(appSource, /staticOpeningElapsedMs/)
  assert.match(appSource, /window\.postMessage\(\{ type: OPENING_COMPLETE_MESSAGE \}/)
  assert.match(preloadSource, /event\.source !== window/)
  assert.match(preloadSource, /ipcRenderer\.send\(OPENING_COMPLETE_IPC_CHANNEL\)/)
})

test('main-renderer opening remains CSS and image based with shared visual and audio timing', () => {
  assert.match(appSource, /import vastLogo from/)
  assert.match(stylesSource, /animation:\s*vast-opening-logo var\(--vast-opening-duration/)
  assert.match(appSource, /vast-opening-overlay platform-\$\{window\.vast\.app\.platform\}/)
  assert.match(stylesSource, /\.vast-opening-overlay\s*\{[^}]*border-radius:\s*0/s)
  assert.match(stylesSource, /\.vast-opening-overlay\.platform-darwin\s*\{[^}]*border-radius:\s*28px/s)
  assert.match(stylesSource, /\.vast-opening-logo-frame\s*\{[^}]*overflow:\s*hidden/s)
  assert.match(stylesSource, /\.vast-opening-logo\s*\{[^}]*transform:\s*translate\(-50%,\s*-50%\)/s)
  assert.match(stylesSource, /animation-delay:\s*var\(--vast-opening-delay/)
  assert.match(appSource, /playOpeningSerenitySound\(openingSoundVolume\)/)
  assert.match(appSource, /openingVolumeToGain\(volume\)/)
  assert.doesNotMatch(appSource, /<video/)
  assert.doesNotMatch(appSource, /vast-opening\.mp4/)
})
