interface Env {
  GITHUB_CLIENT_ID: string
  GITHUB_CLIENT_SECRET: string
  HUB_SIGNING_PRIVATE_KEY_PKCS8?: string
  HUB_SIGNER: Fetcher
  HUB_PUBLIC_RATE_LIMIT: RateLimit
  HUB_AUTH_RATE_LIMIT: RateLimit
  HUB_PUBLISH_RATE_LIMIT: RateLimit
  HUB_REVIEW_RATE_LIMIT: RateLimit
  HUB_REPORT_RATE_LIMIT: RateLimit
  HUB_LEGAL_OPERATOR_NAME: string
  HUB_LEGAL_CONTACT_URL: string
}

declare namespace Cloudflare {
  interface Env {
    GITHUB_CLIENT_ID: string
    GITHUB_CLIENT_SECRET: string
    HUB_SIGNING_PRIVATE_KEY_PKCS8?: string
    HUB_SIGNER: Fetcher
    HUB_PUBLIC_RATE_LIMIT: RateLimit
    HUB_AUTH_RATE_LIMIT: RateLimit
    HUB_PUBLISH_RATE_LIMIT: RateLimit
    HUB_REVIEW_RATE_LIMIT: RateLimit
    HUB_REPORT_RATE_LIMIT: RateLimit
    HUB_LEGAL_OPERATOR_NAME: string
    HUB_LEGAL_CONTACT_URL: string
  }
}
