// Generated by scripts/build-cat-addon-archive.cjs.
export const CAT_ADDON_ARCHIVE_SHA256 = 'cc802bee0f20b83c08b9d046429a296d3970c69458926fff5855c8c594eb1cf3'
export const CAT_ADDON_BUNDLE_VERSION = '2.0.0'
