using System.Diagnostics;
using System.IO.Compression;
using System.Net.Http.Headers;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using static VastUpdaterBootstrapperConstants;

return await VastUpdaterBootstrapper.RunAsync(args);

internal static partial class VastUpdaterBootstrapperConstants
{
  // TargetVersion, DefaultManifestUrl, and LogFileName are generated by
  // VastUpdaterBootstrapperConstants.Generated.cs during release packaging.
  public const string ManifestEnvVar = "VAST_UPDATE_MANIFEST_URL";
}

internal static class VastUpdaterBootstrapper
{
  public static async Task<int> RunAsync(string[] args)
  {
    var options = BootstrapperOptions.Parse(args);
    if (options.ShowHelp)
    {
      PrintHelp();
      return 0;
    }

    using var logger = new BootstrapperLogger(options.LogPath);

    try
    {
      logger.Info($"Starting Vast Browser single-file updater {TargetVersion}.");
      var manifestLocation = ResolveManifestLocation(options, logger);

      logger.Info($"Manifest: {manifestLocation}");
      var manifest = await UpdateManifest.LoadAsync(manifestLocation, logger);
      if (!string.Equals(manifest.Version, TargetVersion, StringComparison.OrdinalIgnoreCase))
      {
        throw new InvalidOperationException($"Manifest targets version '{manifest.Version}', but this updater targets '{TargetVersion}'.");
      }

      var downloadRoot = options.DownloadDirectory ?? Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "Vast",
        "UpdaterDownloads",
        TargetVersion,
        DateTime.UtcNow.ToString("yyyyMMdd-HHmmss"));
      Directory.CreateDirectory(downloadRoot);

      var packageUrl = options.PackageUrl ?? manifest.Package?.Url;
      if (string.IsNullOrWhiteSpace(packageUrl))
      {
        throw new InvalidOperationException("Update manifest is missing package.url.");
      }

      var resolvedPackage = ResourceLocation.Resolve(packageUrl, manifest.SourceLocation);
      var packageName = Path.GetFileName(resolvedPackage.SuggestedFileName);
      if (string.IsNullOrWhiteSpace(packageName)) packageName = $"Vast-{TargetVersion}-update.zip";
      var packagePath = Path.Combine(downloadRoot, packageName);

      logger.Info($"Package: {resolvedPackage.Display}");
      await DownloadResourceAsync(resolvedPackage, packagePath, logger);

      var expectedHash = manifest.Package?.Sha256 ?? string.Empty;
      if (!string.IsNullOrWhiteSpace(expectedHash))
      {
        var actualHash = ComputeSha256(packagePath);
        logger.Info($"Package SHA256: {actualHash}");
        if (!string.Equals(actualHash, expectedHash, StringComparison.OrdinalIgnoreCase))
        {
          throw new InvalidOperationException($"Downloaded package hash mismatch. Expected {expectedHash}, got {actualHash}.");
        }
      }
      else
      {
        throw new InvalidOperationException("Update manifest is missing package.sha256.");
      }

      var extractPath = Path.Combine(downloadRoot, "bundle");
      if (Directory.Exists(extractPath)) Directory.Delete(extractPath, recursive: true);
      Directory.CreateDirectory(extractPath);
      logger.Info($"Extracting update bundle to: {extractPath}");
      ZipFile.ExtractToDirectory(packagePath, extractPath);

      var updaterScript = ResolveBundlePath(extractPath, manifest.Package?.Entrypoint, Path.Combine("Updater", "VastUpdater.ps1"));
      var updaterConfig = ResolveBundlePath(extractPath, manifest.Package?.ConfigPath, Path.Combine("Updater", "updater.config.json"), mustExist: false);
      var payloadPath = ResolveBundlePath(extractPath, manifest.Package?.PayloadPath, Path.Combine($"Vast-{TargetVersion}", "win-unpacked"));

      var exitCode = await RunPowerShellUpdaterAsync(updaterScript, updaterConfig, payloadPath, options, logger);
      if (exitCode != 0)
      {
        throw new InvalidOperationException($"Downloaded Vast updater failed with exit code {exitCode}.");
      }

      var successMessage = options.DryRun
        ? $"Vast Browser dry run completed for version {TargetVersion}. No files were changed."
        : $"Vast Browser updated successfully to version {TargetVersion}.";
      logger.Success(successMessage);
      if (!options.KeepDownloads)
      {
        TryDelete(downloadRoot, logger);
      }

      Console.WriteLine();
      Console.ForegroundColor = ConsoleColor.Green;
      Console.WriteLine(successMessage);
      Console.ResetColor();
      Console.WriteLine($"Bootstrapper log: {logger.Path}");
      return 0;
    }
    catch (Exception error)
    {
      logger.Error(error.Message);
      Console.WriteLine();
      Console.ForegroundColor = ConsoleColor.Red;
      Console.WriteLine("Vast Browser update failed.");
      Console.ResetColor();
      Console.WriteLine(error.Message);
      Console.WriteLine($"Bootstrapper log: {logger.Path}");
      WaitBeforeExitIfInteractive(options);
      return 1;
    }
  }

  private static void WaitBeforeExitIfInteractive(BootstrapperOptions options)
  {
    if (options.NonInteractive || Console.IsInputRedirected)
    {
      return;
    }

    try
    {
      Console.WriteLine();
      Console.WriteLine("Press Enter to close.");
      Console.ReadLine();
    }
    catch
    {
      // If the host cannot read from stdin, keep the logged failure as the source of truth.
    }
  }

  private static async Task DownloadResourceAsync(ResourceLocation location, string destination, BootstrapperLogger logger)
  {
    Directory.CreateDirectory(Path.GetDirectoryName(destination)!);
    if (location.IsLocalFile)
    {
      logger.Info($"Copying local update package to: {destination}");
      File.Copy(location.LocalPath!, destination, overwrite: true);
      return;
    }

    logger.Info($"Downloading update package to: {destination}");
    using var http = new HttpClient();
    http.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue("VastUpdater", TargetVersion));
    using var response = await http.GetAsync(location.Uri, HttpCompletionOption.ResponseHeadersRead);
    response.EnsureSuccessStatusCode();

    var total = response.Content.Headers.ContentLength;
    await using var source = await response.Content.ReadAsStreamAsync();
    await using var target = File.Create(destination);
    var buffer = new byte[1024 * 128];
    long readTotal = 0;
    var lastPercent = -1;
    while (true)
    {
      var read = await source.ReadAsync(buffer);
      if (read <= 0) break;
      await target.WriteAsync(buffer.AsMemory(0, read));
      readTotal += read;
      if (total.HasValue && total.Value > 0)
      {
        var percent = (int) Math.Min(100, readTotal * 100 / total.Value);
        if (percent >= lastPercent + 10 || percent == 100)
        {
          lastPercent = percent;
          logger.Info($"Download progress: {percent}%");
        }
      }
    }
  }

  private static string ResolveManifestLocation(BootstrapperOptions options, BootstrapperLogger logger)
  {
    if (!string.IsNullOrWhiteSpace(options.ManifestUrl))
    {
      return options.ManifestUrl;
    }

    var envManifest = Environment.GetEnvironmentVariable(ManifestEnvVar);
    if (!string.IsNullOrWhiteSpace(envManifest))
    {
      return envManifest;
    }

    var localManifest = FindLocalReleaseManifest();
    if (!string.IsNullOrWhiteSpace(localManifest))
    {
      logger.Info($"Using local release manifest: {localManifest}");
      return localManifest;
    }

    return DefaultManifestUrl;
  }

  private static string? FindLocalReleaseManifest()
  {
    var baseDir = AppContext.BaseDirectory;
    var currentDir = Directory.GetCurrentDirectory();
    var candidates = new[]
    {
      Path.Combine(baseDir, "update-manifest.json"),
      Path.Combine(baseDir, "Downloads", "update-manifest.json"),
      Path.Combine(baseDir, "..", "Downloads", "update-manifest.json"),
      Path.Combine(currentDir, "update-manifest.json"),
      Path.Combine(currentDir, "Downloads", "update-manifest.json"),
      Path.Combine(currentDir, "release", "Downloads", "update-manifest.json")
    };

    foreach (var candidate in candidates)
    {
      var fullPath = Path.GetFullPath(candidate);
      if (File.Exists(fullPath))
      {
        return fullPath;
      }
    }

    return null;
  }

  private static async Task<int> RunPowerShellUpdaterAsync(
    string updaterScript,
    string updaterConfig,
    string payloadPath,
    BootstrapperOptions options,
    BootstrapperLogger logger)
  {
    var arguments = new List<string>
    {
      "-NoProfile",
      "-ExecutionPolicy",
      "Bypass",
      "-File",
      Quote(updaterScript),
      "-TargetVersion",
      TargetVersion,
      "-PayloadPath",
      Quote(payloadPath)
    };

    if (!string.IsNullOrWhiteSpace(updaterConfig) && File.Exists(updaterConfig))
    {
      arguments.Add("-ConfigPath");
      arguments.Add(Quote(updaterConfig));
    }

    arguments.AddRange(options.PowerShellArguments.Select(QuoteIfNeeded));

    logger.Info("Launching downloaded production updater.");
    var start = new ProcessStartInfo
    {
      FileName = "powershell.exe",
      Arguments = string.Join(" ", arguments),
      UseShellExecute = false,
      RedirectStandardOutput = true,
      RedirectStandardError = true,
      CreateNoWindow = false
    };

    using var process = Process.Start(start) ?? throw new InvalidOperationException("Could not start powershell.exe.");
    var outputTask = PipeAsync(process.StandardOutput, logger.Info);
    var errorTask = PipeAsync(process.StandardError, logger.Warn);
    await Task.WhenAll(process.WaitForExitAsync(), outputTask, errorTask);
    logger.Info($"Downloaded updater exit code: {process.ExitCode}");
    return process.ExitCode;
  }

  private static async Task PipeAsync(StreamReader reader, Action<string> write)
  {
    while (!reader.EndOfStream)
    {
      var line = await reader.ReadLineAsync();
      if (!string.IsNullOrWhiteSpace(line)) write(line);
    }
  }

  private static string ResolveBundlePath(string bundleRoot, string? relativePath, string fallback, bool mustExist = true)
  {
    var raw = string.IsNullOrWhiteSpace(relativePath) ? fallback : relativePath;
    var combined = Path.GetFullPath(Path.Combine(bundleRoot, raw));
    var root = Path.GetFullPath(bundleRoot).TrimEnd(Path.DirectorySeparatorChar) + Path.DirectorySeparatorChar;
    if (!combined.StartsWith(root, StringComparison.OrdinalIgnoreCase))
    {
      throw new InvalidOperationException($"Manifest path escapes the update bundle: {raw}");
    }

    if (mustExist && !File.Exists(combined) && !Directory.Exists(combined))
    {
      throw new InvalidOperationException($"Downloaded update bundle is incomplete. Missing: {raw}");
    }

    return combined;
  }

  private static string ComputeSha256(string path)
  {
    using var stream = File.OpenRead(path);
    return Convert.ToHexString(SHA256.HashData(stream)).ToLowerInvariant();
  }

  private static string Quote(string value) => "\"" + value.Replace("\"", "\\\"") + "\"";

  private static string QuoteIfNeeded(string value)
  {
    if (value.StartsWith("-", StringComparison.Ordinal)) return value;
    return Quote(value);
  }

  private static void TryDelete(string path, BootstrapperLogger logger)
  {
    try
    {
      if (Directory.Exists(path)) Directory.Delete(path, recursive: true);
    }
    catch (Exception error)
    {
      logger.Warn($"Could not remove temporary download folder '{path}': {error.Message}");
    }
  }

  private static void PrintHelp()
  {
    Console.WriteLine($"Vast Browser single-file updater {TargetVersion}");
    Console.WriteLine();
    Console.WriteLine("Usage:");
    Console.WriteLine($"  VastUpdater-{TargetVersion}.exe [--manifest-url <url-or-path>] [--package-url <url-or-path>] [updater options]");
    Console.WriteLine();
    Console.WriteLine("Bootstrapper options:");
    Console.WriteLine("  --manifest-url <url-or-path>  Update manifest URL or local manifest path.");
    Console.WriteLine("  --package-url <url-or-path>   Override package URL from manifest.");
    Console.WriteLine("  --download-dir <path>         Folder for downloaded package and extracted bundle.");
    Console.WriteLine("  --keep-downloads              Keep downloaded files after success.");
    Console.WriteLine("  --bootstrap-log-path <path>   Bootstrapper log path.");
    Console.WriteLine("  --help                        Show help.");
    Console.WriteLine();
    Console.WriteLine("Updater pass-through examples:");
    Console.WriteLine("  -InstallPath \"D:\\Apps\\Vast\" -UserDataRoot \"D:\\VastData\" -BackupRoot \"E:\\VastBackups\" -ForceClose -NonInteractive");
    Console.WriteLine();
    Console.WriteLine($"If --manifest-url is omitted, {ManifestEnvVar} is used, then a local release Downloads\\update-manifest.json, then {DefaultManifestUrl}.");
  }
}

internal sealed class BootstrapperOptions
{
  public string? ManifestUrl { get; private set; }
  public string? PackageUrl { get; private set; }
  public string? DownloadDirectory { get; private set; }
  public string? LogPath { get; private set; }
  public bool KeepDownloads { get; private set; }
  public bool DryRun { get; private set; }
  public bool NonInteractive { get; private set; }
  public bool ShowHelp { get; private set; }
  public List<string> PowerShellArguments { get; } = [];

  public static BootstrapperOptions Parse(string[] args)
  {
    var options = new BootstrapperOptions();
    for (var index = 0; index < args.Length; index++)
    {
      var arg = args[index];
      switch (arg.ToLowerInvariant())
      {
        case "--help":
        case "-?":
        case "/?":
          options.ShowHelp = true;
          break;
        case "--manifest-url":
          options.ManifestUrl = RequireValue(args, ref index, arg);
          break;
        case "--package-url":
          options.PackageUrl = RequireValue(args, ref index, arg);
          break;
        case "--download-dir":
          options.DownloadDirectory = RequireValue(args, ref index, arg);
          break;
        case "--bootstrap-log-path":
          options.LogPath = RequireValue(args, ref index, arg);
          break;
        case "--keep-downloads":
          options.KeepDownloads = true;
          break;
        case "--install-path":
          options.PowerShellArguments.Add("-InstallPath");
          options.PowerShellArguments.Add(RequireValue(args, ref index, arg));
          break;
        case "--user-data-root":
          options.PowerShellArguments.Add("-UserDataRoot");
          options.PowerShellArguments.Add(RequireValue(args, ref index, arg));
          break;
        case "--backup-root":
          options.PowerShellArguments.Add("-BackupRoot");
          options.PowerShellArguments.Add(RequireValue(args, ref index, arg));
          break;
        case "--force-close":
          options.PowerShellArguments.Add("-ForceClose");
          break;
        case "--non-interactive":
          options.NonInteractive = true;
          options.PowerShellArguments.Add("-NonInteractive");
          break;
        case "--dry-run":
        case "-dryrun":
          options.DryRun = true;
          options.PowerShellArguments.Add("-DryRun");
          break;
        default:
          if (string.Equals(arg, "-DryRun", StringComparison.OrdinalIgnoreCase))
          {
            options.DryRun = true;
          }
          options.PowerShellArguments.Add(arg);
          break;
      }
    }

    return options;
  }

  private static string RequireValue(string[] args, ref int index, string option)
  {
    if (index + 1 >= args.Length || args[index + 1].StartsWith("-", StringComparison.Ordinal))
    {
      throw new ArgumentException($"{option} requires a value.");
    }

    index++;
    return args[index];
  }
}

internal sealed class UpdateManifest
{
  [JsonIgnore]
  public ResourceLocation SourceLocation { get; private set; } = ResourceLocation.FromPath(Directory.GetCurrentDirectory());

  [JsonPropertyName("version")]
  public string Version { get; set; } = string.Empty;

  [JsonPropertyName("package")]
  public UpdatePackage? Package { get; set; }

  public static async Task<UpdateManifest> LoadAsync(string location, BootstrapperLogger logger)
  {
    var resource = ResourceLocation.Resolve(location, null);
    string json;
    if (resource.IsLocalFile)
    {
      json = await File.ReadAllTextAsync(resource.LocalPath!, Encoding.UTF8);
    }
    else
    {
      using var http = new HttpClient();
      http.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue("VastUpdater", TargetVersion));
      json = await http.GetStringAsync(resource.Uri);
    }

    var manifest = JsonSerializer.Deserialize<UpdateManifest>(json, new JsonSerializerOptions
    {
      PropertyNameCaseInsensitive = true
    }) ?? throw new InvalidOperationException("Could not parse update manifest.");
    manifest.SourceLocation = resource;
    logger.Info($"Manifest version: {manifest.Version}");
    return manifest;
  }
}

internal sealed class UpdatePackage
{
  [JsonPropertyName("url")]
  public string Url { get; set; } = string.Empty;

  [JsonPropertyName("sha256")]
  public string Sha256 { get; set; } = string.Empty;

  [JsonPropertyName("size")]
  public long Size { get; set; }

  [JsonPropertyName("entrypoint")]
  public string Entrypoint { get; set; } = string.Empty;

  [JsonPropertyName("configPath")]
  public string ConfigPath { get; set; } = string.Empty;

  [JsonPropertyName("payloadPath")]
  public string PayloadPath { get; set; } = string.Empty;
}

internal sealed class ResourceLocation
{
  public Uri? Uri { get; }
  public string? LocalPath { get; }
  public bool IsLocalFile => LocalPath is not null;
  public string Display => IsLocalFile ? LocalPath! : Uri!.ToString();
  public string SuggestedFileName => IsLocalFile ? LocalPath! : Uri!.AbsolutePath;

  private ResourceLocation(Uri uri) => Uri = uri;
  private ResourceLocation(string localPath) => LocalPath = Path.GetFullPath(localPath);

  public static ResourceLocation FromPath(string path) => new(path);

  public static ResourceLocation Resolve(string raw, ResourceLocation? baseLocation)
  {
    if (Uri.TryCreate(raw, UriKind.Absolute, out var absolute))
    {
      if (absolute.IsFile) return new ResourceLocation(absolute.LocalPath);
      return new ResourceLocation(absolute);
    }

    if (baseLocation?.Uri is not null)
    {
      return new ResourceLocation(new Uri(baseLocation.Uri, raw));
    }

    if (baseLocation?.LocalPath is not null)
    {
      var parent = File.Exists(baseLocation.LocalPath)
        ? Path.GetDirectoryName(baseLocation.LocalPath)!
        : baseLocation.LocalPath;
      return new ResourceLocation(Path.Combine(parent, raw));
    }

    return new ResourceLocation(raw);
  }
}

internal sealed class BootstrapperLogger : IDisposable
{
  private readonly StreamWriter writer;
  public string Path { get; }

  public BootstrapperLogger(string? requestedPath)
  {
    Path = string.IsNullOrWhiteSpace(requestedPath)
      ? System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Vast", "UpdaterLogs", LogFileName)
      : requestedPath;
    Directory.CreateDirectory(System.IO.Path.GetDirectoryName(Path)!);
    writer = new StreamWriter(File.Open(Path, FileMode.Append, FileAccess.Write, FileShare.ReadWrite), Encoding.UTF8)
    {
      AutoFlush = true
    };
  }

  public void Info(string message) => Write("INFO", message);
  public void Warn(string message) => Write("WARN", message);
  public void Error(string message) => Write("ERROR", message);
  public void Success(string message) => Write("SUCCESS", message);

  private void Write(string level, string message)
  {
    var line = $"[{DateTime.Now:yyyy-MM-dd HH:mm:ss.fff}] [{level}] {message}";
    writer.WriteLine(line);
    Console.WriteLine(line);
  }

  public void Dispose() => writer.Dispose();
}
