/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=admin/wrangler.jsonc --env=staging --include-runtime=false --env-interface=AdminEnv admin-configuration.d.ts` (hash: 8abcdbced9a9157249aa35ee42ae4e83)
interface __BaseEnv_AdminEnv {
	ASSETS: R2Bucket;
	DB: D1Database;
	ADMIN_SOURCE_RATE_LIMIT: RateLimit;
	ADMIN_ACTOR_RATE_LIMIT: RateLimit;
	ADMIN_MUTATION_RATE_LIMIT: RateLimit;
	CONTROL_PANEL_ASSETS: Fetcher;
	ACCESS_AUD: "d57429a0aa7ef593c1a7eac956cfce93eb284f518625454b55b6a25787ef0866";
	ACCESS_TEAM_DOMAIN: "https://vast-browser.cloudflareaccess.com";
	CONTROL_PANEL_ORIGIN: "https://controlpanel-staging.vastbrowser.com";
	ENVIRONMENT: "staging";
	RELAY_KEY_ID: "relay-staging-2026-01";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/admin/index");
	}
	interface Env extends __BaseEnv_AdminEnv {}
}
interface AdminEnv extends __BaseEnv_AdminEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCESS_AUD" | "ACCESS_TEAM_DOMAIN" | "CONTROL_PANEL_ORIGIN" | "ENVIRONMENT" | "RELAY_KEY_ID">> {}
}
